package com.lj.exam.dal.dataobject;

import java.util.Date;

// auto generated imports

/**
 * A data object class directly models database table <tt>exam_record</tt>.
 *
 * This file is generated by <tt>financenet-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>iwallet</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/exam_record.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>financenet-dalgen</tt> 
 * to generate this file.
 *
 */
public class ExamRecordDO {
    
    //========== properties ==========
	
	/**
	 * This property corresponds to db column <tt>id</tt>.
	 */
	private int id;
	/**
	 * This property corresponds to db column <tt>Creat_Time</tt>.
	 */
	private Date creatTime;

	/**
	 * This property corresponds to db column <tt>ExamineRoom_Code</tt>.
	 */
	private String examSiteCode;

	/**
	 * This property corresponds to db column <tt>Course_Code</tt>.
	 */
	private String courseCode;

	/**
	 * This property corresponds to db column <tt>Course_SubCode</tt>.
	 */
	private String courseSubCode;

	/**
	 * This property corresponds to db column <tt>Examinee_Num</tt>.
	 */
	private String examineeNum;

	/**
	 * This property corresponds to db column <tt>Examinee_Name</tt>.
	 */
	private String examineeName;

	/**
	 * This property corresponds to db column <tt>Score</tt>.
	 */
	private Long score;

	/**
	 * This property corresponds to db column <tt>Video</tt>.
	 */
	private String video;

	/**
	 * This property corresponds to db column <tt>File</tt>.
	 */
	private String file;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getCreatTime() {
		return creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	public String getExamSiteCode() {
		return examSiteCode;
	}

	public void setExamSiteCode(String examSiteCode) {
		this.examSiteCode = examSiteCode;
	}

	public String getCourseCode() {
		return courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	public String getCourseSubCode() {
		return courseSubCode;
	}

	public void setCourseSubCode(String courseSubCode) {
		this.courseSubCode = courseSubCode;
	}

	public String getExamineeNum() {
		return examineeNum;
	}

	public void setExamineeNum(String examineeNum) {
		this.examineeNum = examineeNum;
	}

	public String getExamineeName() {
		return examineeName;
	}

	public void setExamineeName(String examineeName) {
		this.examineeName = examineeName;
	}

	public Long getScore() {
		return score;
	}

	public void setScore(Long score) {
		this.score = score;
	}

	public String getVideo() {
		return video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	public String getFile() {
		return file;
	}

	public void setFile(String file) {
		this.file = file;
	}

}
